export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const FETCH_PRODUCT = "FETCH_PRODUCT";
export const PRODUCT_CREATED = "PRODUCT_CREATED";
export const PRODUCT_DELETED = "PRODUCT_DELETED";
export const PRODUCT_UPDATED = "PRODUCT_UPDATED";
